// Generated by view binder compiler. Do not edit!
package com.example.memo.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import com.example.senlonase.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityDetailsProgBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final RecyclerView recyclerView;

  @NonNull
  public final RowToolbarBinding toolbarMain;

  @NonNull
  public final TextView tvHeure;

  @NonNull
  public final TextView tvHypo;

  @NonNull
  public final TextView tvMise;

  @NonNull
  public final TextView tvPartant;

  @NonNull
  public final TextView tvPronostic;

  @NonNull
  public final TextView tvTitle;

  private ActivityDetailsProgBinding(@NonNull RelativeLayout rootView,
      @NonNull RecyclerView recyclerView, @NonNull RowToolbarBinding toolbarMain,
      @NonNull TextView tvHeure, @NonNull TextView tvHypo, @NonNull TextView tvMise,
      @NonNull TextView tvPartant, @NonNull TextView tvPronostic, @NonNull TextView tvTitle) {
    this.rootView = rootView;
    this.recyclerView = recyclerView;
    this.toolbarMain = toolbarMain;
    this.tvHeure = tvHeure;
    this.tvHypo = tvHypo;
    this.tvMise = tvMise;
    this.tvPartant = tvPartant;
    this.tvPronostic = tvPronostic;
    this.tvTitle = tvTitle;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityDetailsProgBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityDetailsProgBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_details_prog, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityDetailsProgBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.recyclerView;
      RecyclerView recyclerView = rootView.findViewById(id);
      if (recyclerView == null) {
        break missingId;
      }

      id = R.id.toolbar_main;
      View toolbarMain = rootView.findViewById(id);
      if (toolbarMain == null) {
        break missingId;
      }
      RowToolbarBinding binding_toolbarMain = RowToolbarBinding.bind(toolbarMain);

      id = R.id.tv_heure;
      TextView tvHeure = rootView.findViewById(id);
      if (tvHeure == null) {
        break missingId;
      }

      id = R.id.tv_hypo;
      TextView tvHypo = rootView.findViewById(id);
      if (tvHypo == null) {
        break missingId;
      }

      id = R.id.tv_mise;
      TextView tvMise = rootView.findViewById(id);
      if (tvMise == null) {
        break missingId;
      }

      id = R.id.tv_partant;
      TextView tvPartant = rootView.findViewById(id);
      if (tvPartant == null) {
        break missingId;
      }

      id = R.id.tv_pronostic;
      TextView tvPronostic = rootView.findViewById(id);
      if (tvPronostic == null) {
        break missingId;
      }

      id = R.id.tv_title;
      TextView tvTitle = rootView.findViewById(id);
      if (tvTitle == null) {
        break missingId;
      }

      return new ActivityDetailsProgBinding((RelativeLayout) rootView, recyclerView,
          binding_toolbarMain, tvHeure, tvHypo, tvMise, tvPartant, tvPronostic, tvTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
