// Generated by view binder compiler. Do not edit!
package com.example.memo.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;

import com.example.memo.R;

import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ItemActuBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final ImageView ivImg;

  @NonNull
  public final LinearLayout rlData;

  @NonNull
  public final TextView tvTitle;

  private ItemActuBinding(@NonNull LinearLayout rootView, @NonNull ImageView ivImg,
      @NonNull LinearLayout rlData, @NonNull TextView tvTitle) {
    this.rootView = rootView;
    this.ivImg = ivImg;
    this.rlData = rlData;
    this.tvTitle = tvTitle;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemActuBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemActuBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_actu, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemActuBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.iv_img;
      ImageView ivImg = rootView.findViewById(id);
      if (ivImg == null) {
        break missingId;
      }

      LinearLayout rlData = (LinearLayout) rootView;

      id = R.id.tv_title;
      TextView tvTitle = rootView.findViewById(id);
      if (tvTitle == null) {
        break missingId;
      }

      return new ItemActuBinding((LinearLayout) rootView, ivImg, rlData, tvTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
