// Generated by view binder compiler. Do not edit!
package com.example.memo.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.Toolbar;
import androidx.viewbinding.ViewBinding;
import com.example.senlonase.R;
import com.example.senlonase.utils.StatusBarView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class RowToolbar4Binding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final ImageView ivBack;

  @NonNull
  public final StatusBarView statusBar;

  @NonNull
  public final Toolbar toolbar;

  @NonNull
  public final ImageView typo;

  private RowToolbar4Binding(@NonNull LinearLayout rootView, @NonNull ImageView ivBack,
      @NonNull StatusBarView statusBar, @NonNull Toolbar toolbar, @NonNull ImageView typo) {
    this.rootView = rootView;
    this.ivBack = ivBack;
    this.statusBar = statusBar;
    this.toolbar = toolbar;
    this.typo = typo;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static RowToolbar4Binding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static RowToolbar4Binding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.row_toolbar4, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static RowToolbar4Binding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.iv_back;
      ImageView ivBack = rootView.findViewById(id);
      if (ivBack == null) {
        break missingId;
      }

      id = R.id.status_bar;
      StatusBarView statusBar = rootView.findViewById(id);
      if (statusBar == null) {
        break missingId;
      }

      id = R.id.toolbar;
      Toolbar toolbar = rootView.findViewById(id);
      if (toolbar == null) {
        break missingId;
      }

      id = R.id.typo;
      ImageView typo = rootView.findViewById(id);
      if (typo == null) {
        break missingId;
      }

      return new RowToolbar4Binding((LinearLayout) rootView, ivBack, statusBar, toolbar, typo);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
