// Generated by view binder compiler. Do not edit!
package com.example.memo.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import com.example.senlonase.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ViewRetryBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final Button btnRetry;

  @NonNull
  public final ImageView iconSad;

  @NonNull
  public final CardView rlRetry;

  @NonNull
  public final TextView textPlaceholder;

  private ViewRetryBinding(@NonNull CardView rootView, @NonNull Button btnRetry,
      @NonNull ImageView iconSad, @NonNull CardView rlRetry, @NonNull TextView textPlaceholder) {
    this.rootView = rootView;
    this.btnRetry = btnRetry;
    this.iconSad = iconSad;
    this.rlRetry = rlRetry;
    this.textPlaceholder = textPlaceholder;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewRetryBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewRetryBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_retry, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewRetryBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btn_retry;
      Button btnRetry = rootView.findViewById(id);
      if (btnRetry == null) {
        break missingId;
      }

      id = R.id.icon_sad;
      ImageView iconSad = rootView.findViewById(id);
      if (iconSad == null) {
        break missingId;
      }

      CardView rlRetry = (CardView) rootView;

      id = R.id.text_placeholder;
      TextView textPlaceholder = rootView.findViewById(id);
      if (textPlaceholder == null) {
        break missingId;
      }

      return new ViewRetryBinding((CardView) rootView, btnRetry, iconSad, rlRetry, textPlaceholder);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
